services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env
    ports:
      - "5432:5432"
  hivemq:
    image: "hivemq/hivemq4"
    ports:
      - "8080:8080"
      - "1883:1883"
